version: '1.0'

services:
  app:
    image: 'd7c497caae62'
    container_name: application
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_PASSWORD=password
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: students_db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password